# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy all app files to the container
COPY . .

# Build the React app for production
RUN npm run build

# Expose the port your app is running on
EXPOSE 3000

# Define the command to run your app
CMD ["npm", "start"]
