# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Copy all app files to the container
COPY . .

RUN npm ci

ENV PORT=3002

# Expose the port your app is running on
EXPOSE 3002

# Define the command to run your app
CMD ["npm", "run", "dev"]
