version: '3'
services:
  backend:
    build:
      context: ./server
    ports:
      - '5000:5000'

  frontend:
    build:
      context: ./client
    ports:
      - '3000:3000'

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
