# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm ci

# Copy all app files to the container
COPY . .

ENV PORT=3000

# Expose the port your app is running on
EXPOSE 3000

# Define the command to run your app
CMD ["npm", "run", "dev"]
